// 对于固定的表头进行定义
 
export const userTableHead = [
    {
        "title":"NotesID",
        "key":"notes_id",
        "dataIndex":"notes_id",
        "width":"15%"
    },
    {
        "title":"用户名称",
        "key":"user_name",
        "dataIndex":"user_name",
        "width":"15%"
    },
    {
        "title":"用户角色",
        "key":"character_name",
        "dataIndex":"character_name",
        "width":"15%"
    },
    {
        "title":"归属条线",
        "key":"group_name",
        "dataIndex":"group_name",
        "width":"10%"
    },
    {
        "title":"归属机构",
        "key":"org_name",
        "dataIndex":"org_name",
        "width":"15%"
    },
    {
        "title":"直属上级",
        "key":"org_manager",
        "dataIndex":"org_manager",
        "width":"15%"
    },
    {
        "title":"操作",
        "key":"org_operation",
        "dataIndex":"org_operation",
        "width":"20%"
    }
]