"""
Django settings for DemoServer project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from kpi_server.errMsg import KPI_ERROR_MESSAGES

import os
from dotenv import load_dotenv

# 读取环境配置
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 此处引入pymysql作为依赖
import pymysql
pymysql.install_as_MySQLdb()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7mxm2bo&v+_7z*9=23*0six)-ck3m(8#xs@mxn(#dz4+yymb0s'

# CRYPTO SETTINGS
# CRYPTO_KEY = '@aR9*p3K@L2qJ7!W'
CRYPTO_KEY = os.getenv('SERVER_CRYPTO_KEY')
# CRYPTO_IV = 'X5yD!w*Q8Fv@2S7M'
CRYPTO_IV = os.getenv('X5yD!w*Q8Fv@2S7M')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_swagger',
    'rest_framework',
    'kpi_server',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'DemoServer.corsmiddleware.CorsMiddleware'
]

ROOT_URLCONF = 'DemoServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DemoServer.wsgi.application'

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    'http://localhost:8080',
    'http://localhost:3000',
    'http://kpi.bearman.xyz',
    'https://kpi.bearman.xyz',
    'http://106.15.120.71:80',
    'https://106.15.120.71:443'
]
CORS_ALLOW_HEADERS = [
    'Authorization',
    'X-Refresh-Token',
    'Content-Type'
]
CORS_EXPOSE_HEADERS = [
    'Authorization',
    'X-Refresh-Token',
]
CORS_ALLOW_METHODS = ("POST","GET")


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.mysql',
        'NAME':os.getenv('MYSQL_DEFAULT_DB'),
        'USER':'root',
        'PASSWORD':os.getenv('MYSQL_PWD'),
        'HOST':os.getenv('MYSQL_HOST'),
        'PORT':os.getenv('MYSQL_PORT')
    },
    'kpi_db':{
        'ENGINE':'django.db.backends.mysql',
        'NAME':os.getenv('MYSQL_DB'),
        'USER':'root',
        'PASSWORD':os.getenv('MYSQL_PWD'),
        'HOST':os.getenv('MYSQL_HOST'),
        'PORT':os.getenv('MYSQL_PORT')
    }
}
DATABASES_APPS_MAPPING = {
    'kpi_server':os.getenv('MYSQL_DB')
}

# 插入数据路由

DATABASE_ROUTERS = ['DemoServer.routers.DatabaseAppRouter']

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = { 
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema' ,
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework_simplejwt.authentication.JWTAuthentication']
}

# 配置simple JWT
SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24), #设定访问令牌有效时间
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  #设定刷新令牌有效期
    'ROTATE_REFRESH_TOKENS': True,
}

AUTH_USER_MODEL = 'kpi_server.UserAuth'
AUTHENTICATION_BACKENDS = ['kpi_server.backends.CustomAuthBackend']

# 配置KPI的信息码
KPI_ERROR_MESSAGES = KPI_ERROR_MESSAGES