# Generated by Django 4.1 on 2023-08-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_num', models.CharField(max_length=10, verbose_name='机构编号')),
                ('org_name', models.CharField(max_length=64, verbose_name='机构名称')),
                ('parent_org_id', models.CharField(max_length=8, verbose_name='上级机构编号')),
                ('org_level', models.IntegerField(verbose_name='机构层级')),
                ('org_group', models.IntegerField(verbose_name='机构分组')),
                ('org_manager', models.CharField(max_length=8, verbose_name='机构负责人id')),
                ('org_create', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('org_update', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('org_status', models.IntegerField(verbose_name='机构状态')),
                ('org_ext_info', models.CharField(max_length=64, verbose_name='机构扩展字段')),
            ],
            options={
                'db_table': 'org_info',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_id', models.CharField(max_length=8, verbose_name='用户notesid')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户姓名')),
                ('user_belong_org', models.CharField(max_length=10, verbose_name='用户归属机构')),
                ('user_belong_group', models.IntegerField(verbose_name='用户所属分组/条线')),
                ('user_character', models.IntegerField(verbose_name='用户角色')),
                ('user_create', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('user_update', models.DateField(verbose_name='修改时间')),
                ('user_states', models.IntegerField(verbose_name='用户状态')),
                ('user_ext_info', models.CharField(max_length=65, verbose_name='用户信息补充字段')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
