# Generated by Django 4.1 on 2023-09-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_num",
                    models.CharField(max_length=10, unique=True, verbose_name="指标编号"),
                ),
                ("index_class", models.IntegerField(verbose_name="指标分类-财务效益等")),
                ("belong_line", models.IntegerField(verbose_name="归属条线-企金、零售、同业其他等")),
                ("index_unit", models.CharField(max_length=10, verbose_name="指标单位")),
                ("index_name", models.CharField(max_length=64, verbose_name="指标名称")),
                ("index_type", models.IntegerField(verbose_name="指标类型-个人、机构")),
                ("need_focus", models.IntegerField(verbose_name="是否重点指标")),
                ("need_show", models.IntegerField(verbose_name="是否需要展示")),
                ("is_db", models.IntegerField(verbose_name="是否首页数据看板")),
                (
                    "index_create",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("index_update", models.DateField(auto_now=True, verbose_name="修改时间")),
                ("index_status", models.IntegerField(verbose_name="指标状态")),
                (
                    "index_ext_info",
                    models.CharField(max_length=64, verbose_name="扩展字段"),
                ),
            ],
            options={
                "db_table": "index_info",
            },
        ),
        migrations.CreateModel(
            name="IndexDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.IntegerField(verbose_name="上传记录id")),
                ("index_id", models.IntegerField(verbose_name="指标id")),
                ("detail_date", models.DateField(verbose_name="详情归属月份")),
                ("detail_type", models.IntegerField(verbose_name="详情种类,是实际值还是计划值等")),
                ("detail_class", models.IntegerField(verbose_name="详情归属，是个人还是机构")),
                (
                    "detail_belong",
                    models.CharField(
                        max_length=10, verbose_name="详情归属对象, 机构编号或者notesid"
                    ),
                ),
                (
                    "detail_create",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("detail_update", models.DateField(auto_now=True, verbose_name="修改时间")),
                ("detail_status", models.IntegerField(verbose_name="详情状态")),
                (
                    "detail_ext_info",
                    models.CharField(max_length=64, verbose_name="扩展字段"),
                ),
            ],
            options={
                "db_table": "index_detail",
            },
        ),
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_num",
                    models.CharField(max_length=10, unique=True, verbose_name="机构编号"),
                ),
                ("org_name", models.CharField(max_length=64, verbose_name="机构名称")),
                (
                    "parent_org_id",
                    models.CharField(max_length=8, verbose_name="上级机构编号"),
                ),
                ("org_level", models.IntegerField(verbose_name="机构层级")),
                ("org_group", models.IntegerField(verbose_name="机构分组")),
                ("org_manager", models.CharField(max_length=8, verbose_name="机构负责人id")),
                (
                    "org_create",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("org_update", models.DateField(auto_now=True, verbose_name="修改时间")),
                ("org_status", models.IntegerField(verbose_name="机构状态")),
                (
                    "org_ext_info",
                    models.CharField(max_length=64, verbose_name="机构扩展字段"),
                ),
            ],
            options={
                "db_table": "org_info",
            },
        ),
        migrations.CreateModel(
            name="UploadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_id",
                    models.CharField(max_length=10, unique=True, verbose_name="历史记录编号"),
                ),
                ("record_name", models.CharField(max_length=64, verbose_name="上传记录名称")),
                ("history_active", models.IntegerField(verbose_name="该版本是否对外生效")),
                (
                    "histroy_update_user",
                    models.CharField(max_length=10, verbose_name="历史上传人员notesid"),
                ),
                (
                    "histroy_update_fileName",
                    models.CharField(max_length=128, verbose_name="历史记录上传文件名称"),
                ),
                ("histroy_status", models.IntegerField(verbose_name="历史记录状态")),
                (
                    "histroy_create",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "histroy_update",
                    models.DateField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "histroy_ext_info",
                    models.CharField(max_length=64, verbose_name="历史记录扩展字段"),
                ),
            ],
            options={
                "db_table": "upload_histroy",
            },
        ),
        migrations.CreateModel(
            name="UploadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_id",
                    models.CharField(max_length=10, unique=True, verbose_name="上传记录编号"),
                ),
                ("record_class", models.IntegerField(verbose_name="上传记录分类")),
                ("record_name", models.CharField(max_length=64, verbose_name="上传记录名称")),
                (
                    "record_update_user",
                    models.CharField(max_length=10, verbose_name="上传用户notesid"),
                ),
                (
                    "record_update_time",
                    models.DateTimeField(auto_now=True, verbose_name="上传时间"),
                ),
                (
                    "record_update_active",
                    models.IntegerField(verbose_name="该条记录是否对外生效"),
                ),
                ("record_update_status", models.IntegerField(verbose_name="该条记录状态")),
                (
                    "record_create",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("record_update", models.DateField(auto_now=True, verbose_name="修改时间")),
                (
                    "record_update_ext_info",
                    models.CharField(max_length=64, verbose_name="扩展字段"),
                ),
            ],
            options={
                "db_table": "upload_record",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes_id",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="用户notesid"
                    ),
                ),
                ("user_name", models.CharField(max_length=64, verbose_name="用户姓名")),
                (
                    "user_belong_org",
                    models.CharField(max_length=10, verbose_name="用户归属机构"),
                ),
                ("user_belong_group", models.IntegerField(verbose_name="用户所属分组/条线")),
                ("user_character", models.IntegerField(verbose_name="用户角色")),
                (
                    "user_create",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("user_update", models.DateField(verbose_name="修改时间")),
                ("user_state", models.IntegerField(verbose_name="用户状态")),
                (
                    "user_ext_info",
                    models.CharField(max_length=64, verbose_name="用户信息补充字段"),
                ),
            ],
            options={
                "db_table": "user_info",
            },
        ),
    ]
