# Generated by Django 4.1 on 2023-09-07 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userauth",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="userauth",
            name="password",
        ),
    ]
