# Generated by Django 4.1 on 2023-09-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdetail',
            name='record_id',
            field=models.CharField(max_length=10, verbose_name='上传记录编号'),
        ),
    ]
