# Generated by Django 4.1 on 2023-09-01 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="org",
            old_name="org_status",
            new_name="org_state",
        ),
    ]
