# Generated by Django 4.1 on 2023-09-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_server', '0002_alter_uploaddetail_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddetail',
            name='detail_update_fileMD5',
            field=models.CharField(default='', help_text='文件MD5值', max_length=128),
        ),
        migrations.AlterField(
            model_name='uploaddetail',
            name='detail_id',
            field=models.CharField(help_text='历史记录编号', max_length=48, unique=True),
        ),
    ]
