# Generated by Django 4.1 on 2023-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0002_index_indexdetail_uploadhistory_uploadrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="index_num",
            field=models.CharField(max_length=10, unique=True, verbose_name="指标编号"),
        ),
        migrations.AlterField(
            model_name="org",
            name="org_num",
            field=models.CharField(max_length=10, unique=True, verbose_name="机构编号"),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="history_id",
            field=models.CharField(max_length=10, unique=True, verbose_name="历史记录编号"),
        ),
        migrations.AlterField(
            model_name="uploadrecord",
            name="record_id",
            field=models.CharField(max_length=10, unique=True, verbose_name="上传记录编号"),
        ),
        migrations.AlterField(
            model_name="users",
            name="notes_id",
            field=models.CharField(max_length=8, unique=True, verbose_name="用户notesid"),
        ),
    ]
