# Generated by Django 4.1 on 2023-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0002_rename_org_status_org_org_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_name", models.CharField(max_length=64, verbose_name="码值含义")),
                ("ref_code", models.IntegerField(verbose_name="码值")),
                ("ref_type", models.CharField(max_length=64, verbose_name="码值用途")),
                ("ref_state", models.IntegerField(verbose_name="是否有效")),
                ("ref_ext", models.CharField(max_length=128, verbose_name="码值额外描述")),
            ],
            options={
                "db_table": "reference_code",
            },
        ),
    ]
