# Generated by Django 4.1 on 2023-09-01 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0003_reference"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reference",
            unique_together={("ref_type", "ref_code")},
        ),
    ]
