# Generated by Django 4.1 on 2023-09-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_server', '0003_uploaddetail_detail_update_filemd5_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexdetail',
            old_name='record_id',
            new_name='detail_id',
        ),
    ]
