# Generated by Django 4.1 on 2023-09-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0003_usertoken_login_err"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_mark", models.CharField(help_text="看板标识", max_length=48)),
                ("db_name", models.CharField(help_text="看板名称", max_length=128)),
                ("db_class", models.IntegerField(help_text="数据分类")),
                ("index_num", models.CharField(help_text="关联指标", max_length=256)),
                ("db_func", models.CharField(help_text="对应方法", max_length=64)),
                ("db_state", models.IntegerField(help_text="看板状态")),
                ("db_ext", models.CharField(help_text="其他额外描述", max_length=128)),
                ("db_create", models.DateTimeField(help_text="创建时间")),
                ("db_update", models.DateTimeField(help_text="更新时间")),
            ],
            options={
                "db_table": "dashboard_map",
            },
        ),
    ]
