# Generated by Django 4.1 on 2023-09-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_server', '0004_alter_indexdetail_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdetail',
            name='detail_value',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='指标具体值'),
        ),
    ]
