# Generated by Django 4.1 on 2023-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0004_dashboardmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeMsg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("err_code", models.IntegerField(help_text="回复代码")),
                ("code_type", models.IntegerField(help_text="代码分类")),
                ("err_msg", models.CharField(help_text="错误信息", max_length=128)),
                ("err_ext", models.CharField(help_text="额外内容", max_length=128)),
            ],
            options={
                "db_table": "code_msg",
            },
        ),
    ]
