# Generated by Django 4.1 on 2024-01-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0005_alter_indexdetail_detail_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="index",
            name="parent_index",
            field=models.CharField(
                blank=True, help_text="上级指标", max_length=10, null=True
            ),
        ),
    ]
