# Generated by Django 4.1 on 2023-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_server', '0005_alter_indexdetail_detail_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户姓名')),
                ('notes_id', models.CharField(max_length=8, unique=True, verbose_name='用户notesid')),
                ('password', models.CharField(max_length=128, verbose_name='用户密码')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
