CREATE TABLE IF NOT EXISTS `INDEX_UPLOAD_RECORD` (
    `ID` INT NOT NULL AUTO_INCREMENT COMMENT '上传记录id',
    `RECORD_ID` VARCHAR(10) NOT NULL COMMENT '上传记录编号',
    `RECORD_CLASS` INT COMMENT '上传记录分类，例如企金等',
    `RECORD_NAME` VARCHAR(64) NOT NULL COMMENT '上传记录名称',
    `RECORD_UPDATE_USER` VARCHAR(8) COMMENT '上传记录人员',
    `RECORD_UPDATE_TIME` DATE COMMENT '上传记录时间',
    `RECORD_UPDATE_ACTIVE` INT COMMENT '该条记录是否对外生效',
    `RECORD_UPDATE_STATUS` INT COMMENT '该条记录状态',
    `RECORD_UPDATE_EXT_INFO` VARCHAR(64) COMMENT '上传记录扩展字段',
    PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;