CREATE TABLE IF NOT EXISTS `INDEX_UPLOAD_HISTORY` (
    `ID` INT NOT NULL AUTO_INCREMENT COMMENT '历史记录编号',
    `RECORD_ID` VARCHAR(10) NOT NULL COMMENT '历史-上传记录编号',
    `IS_ACTIVE` INT COMMENT '该版本是否对外生效',
    `HISTORY_UPDATE_USER` VARCHAR(8) COMMENT '历史-上传记录人员',
    `HISTORY_FILE_NAME` VARCHAR(128) COMMENT '历史-上传文件名称',
    `HISTORY_STATUS` INT COMMENT '历史记录状态',
    `HISTORY_EXT_INFO` VARCHAR(64) COMMENT '历史记录扩展字段',
    PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;