CREATE TABLE IF NOT EXISTS `INDEX_DETAIL_TABLE` (
    `ID` INT NOT NULL AUTO_INCREMENT COMMENT '指标记录id',
    `INDEX_RECORD_ID` VARCHAR(10) NOT NULL COMMENT '包含指标的上传文件记录ID',
    `INDEX_ID` INT NOT NULL COMMENT '指标id',
    `INDEX_DETAIL_DATE` DATE NOT NULL COMMENT '指标归属月份',
    `INDEX_DETAIL_TYPE` INT COMMENT '指标种类,实际值还是计划值',
    `INDEX_DETAIL_CLASS` INT COMMENT '指标归属个人还是机构',
    `INDEX_DETAIL_TARGET` VARCHAR(12) COMMENT '指标归属对象编号，机构编号/notesid等',
    `INDEX_DETAIL_CREATE` DATE COMMENT '创建时间',
    `INDEX_DETAIL_UPDATE` DATE COMMENT '修改时间',
    `INDEX_DETAIL_STATUS` INT COMMENT '指标记录状态',
    `INDEX_DETAIL_EXT_INFO` VARCHAR(64) COMMENT '指标记录扩展字段',
    PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;