CREATE TABLE IF NOT EXISTS `USER_INFO_TABLE` (
    `ID` INT NOT NULL AUTO_INCREMENT COMMENT '用户id',
    `NOTESID` VARCHAR(8) NOT NULL COMMENT '用户notesid',
    `USER_NAME` VARCHAR(64) NOT NULL COMMENT '用户姓名',
    -- `BELONG_ORG` INT COMMENT '归属机构',
    -- `BELONG_GROUP` VARCHAR(64) COMMENT '归属分组'
    -- `BELONG_BU` INT COMMENT '归属条线',
    -- `USER_CHAR` INT COMMENT '用户角色',
    `USER_CREATE` DATE NOT NULL COMMENT '创建时间',
    `USER_UPDATE` DATE COMMENT '修改时间',
    `USER_STATUS` INT COMMENT '用户状态',
    `USER_EXT_INFO` VARCHAR(65) COMMENT '用户扩展信息',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
