# Generated by Django 4.1 on 2023-09-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploaddetail',
            table='upload_detail',
        ),
    ]
