# Generated by Django 4.1 on 2024-03-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0008_factorconfig_scoreinstanceinfo_scoremethod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factorconfig",
            name="factor_express",
            field=models.JSONField(help_text="因子计算表达式", max_length=512),
        ),
    ]
