# Generated by Django 4.1 on 2024-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0009_alter_factorconfig_factor_express"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreruledetail",
            name="rule_id",
            field=models.CharField(default="0", help_text="对应模版id", max_length=24),
        ),
        migrations.AlterField(
            model_name="scoremethod",
            name="method_sc_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="评价方式得分上限",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scoremethod",
            name="method_sc_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="评价方式得分下限",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scoreruledetail",
            name="detail_sc_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="考核指标得分上线",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scoreruledetail",
            name="detail_sc_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="考核指标得分下限",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scoreruledetail",
            name="detail_wg_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="考核指标权重上限",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scoreruledetail",
            name="detail_wg_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="考核指标权重下限",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scoreruledetail",
            name="detail_wg_std",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="考核指标标准权重",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scoreruledetail",
            name="detail_wg_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="考核指标权重",
                max_digits=10,
                null=True,
            ),
        ),
    ]
