# Generated by Django 4.1 on 2024-03-04 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0010_scoreruledetail_rule_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScoreInstanceInfo",
        ),
        migrations.DeleteModel(
            name="ScoreRuleDetail",
        ),
    ]
