# Generated by Django 4.1 on 2024-03-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0011_delete_scoreinstanceinfo_delete_scoreruledetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreRuleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detail_id",
                    models.CharField(help_text="考核id", max_length=24, unique=True),
                ),
                ("rule_id", models.CharField(help_text="对应模版id", max_length=24)),
                (
                    "parent_id",
                    models.CharField(
                        blank=True, help_text="父级内容id", max_length=24, null=True
                    ),
                ),
                (
                    "parent_class",
                    models.CharField(
                        blank=True, help_text="父级内容类别", max_length=96, null=True
                    ),
                ),
                ("detail_level", models.IntegerField(help_text="考核指标等级")),
                (
                    "detail_wg_std",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标标准权重",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_wg_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标权重",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_wg_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标权重下限",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_wg_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标权重上限",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_sc_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标得分下限",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_sc_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标得分上线",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_ext_info",
                    models.CharField(
                        blank=True, help_text="补充字段", max_length=512, null=True
                    ),
                ),
            ],
            options={
                "db_table": "score_rule_detail",
            },
        ),
        migrations.CreateModel(
            name="ScoreRuleInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(help_text="分解实例id", max_length=24, unique=True),
                ),
                ("rule_id", models.CharField(help_text="对应模版id", max_length=24)),
                (
                    "instance_parent",
                    models.CharField(help_text="父级实例id", max_length=24),
                ),
                ("instance_state", models.IntegerField(help_text="实例状态")),
                ("instance_period_st", models.DateTimeField(help_text="考核实例开始日期")),
                ("instance_period_end", models.DateTimeField(help_text="考核实例结束日期")),
                ("instance_org", models.CharField(help_text="实例归属机构", max_length=24)),
                ("instance_update_dt", models.DateTimeField(help_text="实例更新日期")),
                (
                    "instance_update_usr",
                    models.CharField(help_text="实例更新人员", max_length=24),
                ),
                (
                    "instance_ext_info",
                    models.CharField(
                        blank=True, help_text="扩展字段", max_length=512, null=True
                    ),
                ),
            ],
            options={
                "db_table": "score_rule_instance",
            },
        ),
    ]
