# Generated by Django 4.1 on 2024-03-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0012_scoreruledetail_scoreruleinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreruleinfo",
            name="rule_ext_info",
            field=models.CharField(
                blank=True, help_text="补充字段", max_length=512, null=True
            ),
        ),
    ]
