# Generated by Django 4.1 on 2024-03-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0013_alter_scoreruleinfo_rule_ext_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreruleinfo",
            name="rule_mark",
            field=models.CharField(
                blank=True, help_text="模板备注", max_length=256, null=True
            ),
        ),
    ]
