# Generated by Django 4.1 on 2024-03-05 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0014_alter_scoreruleinfo_rule_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreruledetail",
            name="detail_title",
            field=models.CharField(
                default=django.utils.timezone.now, help_text="考核指标名称", max_length=96
            ),
            preserve_default=False,
        ),
    ]
