# Generated by Django 4.1 on 2024-03-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0015_scoreruledetail_detail_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoremethod",
            name="method_ext_info",
            field=models.CharField(
                blank=True, help_text="补充字段", max_length=512, null=True
            ),
        ),
    ]
