# Generated by Django 4.1 on 2024-03-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0016_alter_scoremethod_method_ext_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoremethod",
            name="method_express",
            field=models.JSONField(help_text="计算表达式"),
        ),
    ]
