# Generated by Django 4.1 on 2024-03-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0017_alter_scoremethod_method_express"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factorconfig",
            name="factor_ext_info",
            field=models.CharField(
                blank=True, help_text="补充字段", max_length=512, null=True
            ),
        ),
    ]
