# Generated by Django 4.1 on 2024-03-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0019_factorconfig_factor_logic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factorconfig",
            name="factor_logic",
        ),
        migrations.AddField(
            model_name="factorconfig",
            name="factor_cal_logic",
            field=models.IntegerField(default=1, help_text="逻辑运算逻辑"),
        ),
        migrations.AddField(
            model_name="factorconfig",
            name="factor_org_logic",
            field=models.IntegerField(default=1, help_text="目标机构逻辑"),
        ),
        migrations.AddField(
            model_name="factorconfig",
            name="factor_time_logic",
            field=models.IntegerField(default=1, help_text="时间逻辑"),
        ),
    ]
