# Generated by Django 4.1 on 2024-03-05 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0020_remove_factorconfig_factor_logic_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FactorConfig",
        ),
        migrations.DeleteModel(
            name="ScoreMethod",
        ),
        migrations.DeleteModel(
            name="ScoreRuleDetail",
        ),
        migrations.DeleteModel(
            name="ScoreRuleInfo",
        ),
        migrations.DeleteModel(
            name="ScoreRuleInstance",
        ),
    ]
