# Generated by Django 4.1 on 2024-03-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_server", "0021_delete_factorconfig_delete_scoremethod_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor_id", models.CharField(help_text="因子id", max_length=24)),
                ("factor_name", models.CharField(help_text="因子名称", max_length=128)),
                ("factor_class", models.IntegerField(default=1, help_text="因子分类")),
                ("factor_time_logic", models.IntegerField(default=1, help_text="时间逻辑")),
                (
                    "factor_org_logic",
                    models.IntegerField(default=1, help_text="目标机构逻辑"),
                ),
                (
                    "factor_cal_logic",
                    models.IntegerField(default=1, help_text="逻辑运算逻辑"),
                ),
                (
                    "factor_express",
                    models.JSONField(help_text="因子计算表达式", max_length=512),
                ),
                ("factor_update_dt", models.DateTimeField(help_text="因子更新时间")),
                (
                    "factor_update_usr",
                    models.CharField(help_text="因子更新人", max_length=24),
                ),
                (
                    "factor_ext_info",
                    models.CharField(
                        blank=True, help_text="补充字段", max_length=512, null=True
                    ),
                ),
            ],
            options={
                "db_table": "factor_config",
            },
        ),
        migrations.CreateModel(
            name="ScoreMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_id", models.CharField(help_text="评价方式id", max_length=24)),
                ("detail_id", models.CharField(help_text="关联考核指标id", max_length=24)),
                ("method_title", models.CharField(help_text="评价方式名称", max_length=128)),
                ("method_desc", models.CharField(help_text="评价方式描述", max_length=256)),
                (
                    "method_sc_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="评价方式得分下限",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "method_sc_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="评价方式得分上限",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("method_express", models.JSONField(help_text="计算表达式")),
                (
                    "method_ext_info",
                    models.CharField(
                        blank=True, help_text="补充字段", max_length=512, null=True
                    ),
                ),
            ],
            options={
                "db_table": "score_method",
            },
        ),
        migrations.CreateModel(
            name="ScoreRuleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detail_id",
                    models.CharField(help_text="考核id", max_length=24, unique=True),
                ),
                ("rule_id", models.CharField(help_text="对应模版id", max_length=24)),
                (
                    "parent_id",
                    models.CharField(
                        blank=True, help_text="父级内容id", max_length=24, null=True
                    ),
                ),
                (
                    "parent_class",
                    models.CharField(
                        blank=True, help_text="父级内容类别", max_length=96, null=True
                    ),
                ),
                ("detail_title", models.CharField(help_text="考核指标名称", max_length=96)),
                ("detail_level", models.IntegerField(help_text="考核指标等级")),
                (
                    "detail_wg_std",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标标准权重",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_wg_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标权重",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_wg_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标权重下限",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_wg_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标权重上限",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_sc_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标得分下限",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_sc_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="考核指标得分上线",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detail_ext_info",
                    models.CharField(
                        blank=True, help_text="补充字段", max_length=512, null=True
                    ),
                ),
            ],
            options={
                "db_table": "score_rule_detail",
            },
        ),
        migrations.CreateModel(
            name="ScoreRuleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(help_text="模板id", max_length=24, unique=True),
                ),
                ("rule_name", models.CharField(help_text="模板名称", max_length=128)),
                ("rule_state", models.IntegerField(help_text="模板状态")),
                ("rule_update_dt", models.DateTimeField(help_text="更新时间")),
                ("rule_update_usr", models.CharField(help_text="更新人", max_length=24)),
                ("rule_sum", models.IntegerField(blank=True, help_text="模板总权重")),
                (
                    "rule_mark",
                    models.CharField(
                        blank=True, help_text="模板备注", max_length=256, null=True
                    ),
                ),
                (
                    "rule_ext_info",
                    models.CharField(
                        blank=True, help_text="补充字段", max_length=512, null=True
                    ),
                ),
            ],
            options={
                "db_table": "score_rule_info",
            },
        ),
        migrations.CreateModel(
            name="ScoreRuleInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(help_text="分解实例id", max_length=24, unique=True),
                ),
                ("rule_id", models.CharField(help_text="对应模版id", max_length=24)),
                (
                    "instance_parent",
                    models.CharField(help_text="父级实例id", max_length=24),
                ),
                ("instance_state", models.IntegerField(help_text="实例状态")),
                ("instance_period_st", models.DateTimeField(help_text="考核实例开始日期")),
                ("instance_period_end", models.DateTimeField(help_text="考核实例结束日期")),
                ("instance_org", models.CharField(help_text="实例归属机构", max_length=24)),
                ("instance_update_dt", models.DateTimeField(help_text="实例更新日期")),
                (
                    "instance_update_usr",
                    models.CharField(help_text="实例更新人员", max_length=24),
                ),
                (
                    "instance_ext_info",
                    models.CharField(
                        blank=True, help_text="扩展字段", max_length=512, null=True
                    ),
                ),
            ],
            options={
                "db_table": "score_rule_instance",
            },
        ),
    ]
